### PR TITLE
Update rules

### PR DESCRIPTION
**Pull request by alexmyczko**
wow this will need be replaced with something simpler, but best to rename your debian/ to deb/ as in laidout, and later drop it completely

### CODE REVIEW

**Comment by tomlechner** [comment]
Moving debian to deb done.

If I understand, your intent would be to have 2 packages, one for Laidout, and one for Laxkit?
What do you mean something simpler?
In this pr, is there a reason to remove all the comments? I only come back to that file once every few years, and the comments help.

**Comment by alexmyczko** [comment]
ideally  the rules file should be something like https://sources.debian.org/src/protracker/2.3d.r147-1/debian/rules/

**Comment by tomlechner** [comment]
Yes that would be simpler. I trimmed the rules file a little bit.

If current standard practice has almost everything replaced with %: dh $@, how are the necessary custom commands handled? Honestly I've never really understood the dh_* things. I usually work it to the point where I can get a .deb out of it, then promptly forget about it completely.

**Comment by tomlechner** [comment]
Updated prs welcome!

**Comment by tomlechner** [comment]
Closing due to age. If anyone can help get Laidout into the Debian repository, I'd love to talk. Please feel free to resubmit this pr against current code.

**Pull request closed without merging**
